name: Pull Request Workflow

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

jobs:
  launch_test:
    if: startsWith(${{ github.head.ref }}, 'feature/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x, 16.x]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run test
